apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ielts-ai

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - livekit-agent-deployment.yaml
  - ingress.yaml

images:
  - name: kyawzayarsoe/ielts-ai-backend
    newTag: latest
  - name: kyawzayarsoe/ielts-ai-frontend
    newTag: latest
  - name: kyawzayarsoe/ielts-ai-livekit-agent
    newTag: latest

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: ielts-ai
