apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ielts-ai

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - ollama-deployment.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

images:
  - name: kyawzayarsoe/ielts-ai-ollama
    newName: kyawzayarsoe/ielts-ai-ollama
    newTag: latest
  - name: kyawzayarsoe/ielts-ai-backend
    newName: kyawzayarsoe/ielts-ai-backend
    newTag: latest
  - name: kyawzayarsoe/ielts-ai-frontend
    newName: kyawzayarsoe/ielts-ai-frontend
    newTag: latest

commonLabels:
  app.kubernetes.io/managed-by: kustomize
